version: '3.1'

services:
  database:
    image: postgres:17.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=student_db
    ports:
      - "5435:5432"